version: "3.7"

services:
  app:
    image: node:18.4-alpine
    command: sh -c "yarn run dev"
    ports:
      - "4000:4000"
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - ./.env

  redis:
    image: redislabs/rejson:latest
    ports:
      - "6379:6379"